# Generated by Django 4.2.17 on 2025-01-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muzeum', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artwork',
            new_name='Exhibits',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='artwork',
            new_name='exhibit',
        ),
    ]
