# Generated by Django 4.2.17 on 2025-01-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzeum', '0002_rename_artwork_exhibits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
