# Generated by Django 4.2.17 on 2025-01-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzeum', '0003_alter_history_end_date_alter_history_start_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='artist',
            name='valid_birth_year',
        ),
        migrations.RemoveConstraint(
            model_name='artist',
            name='valid_death_year',
        ),
        migrations.RemoveConstraint(
            model_name='artist',
            name='valid_age',
        ),
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.CheckConstraint(check=models.Q(('birth_year__gte', 0)), name='valid_birth_year'),
        ),
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.CheckConstraint(check=models.Q(('death_year__gte', 0)), name='valid_death_year'),
        ),
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.CheckConstraint(check=models.Q(('death_year__gte', models.F('birth_year'))), name='valid_age'),
        ),
    ]
